base_model_dir: "/media/jczars/4C22F02A22F01B22/Ensembler_pollen_classification/Reports_FT/"
data_base_dir: "/media/jczars/4C22F02A22F01B22/Ensembler_pollen_classification/BD/CPD1_Dn_VTcr_111124/EQUATORIAL_R/"
committee_networks:
  - 0_DenseNet201
  - 2_MobileNet
  - 4_InceptionV3
excel_file: "3_ensemble/Reports/EQUATORIAL_ens_111124.xlsx"
BATCH: 16
INPUT_SIZE: [224, 224]
