path_model: "./results/phase3/reports_cr_400/0_DenseNet201/0_DenseNet201_bestLoss_1.keras"
nome: "GradCAM_class_wrong_k1.png"
conv_layer_name: "relu"
img_size: 224

path_data: "./BD/CPD1_Cr_Rs/"
images_labels:
- "ceratonia/Fab.C.silX400wF(479)(0)E-9.png"
- "eucalyptus/Myr.E.camaX400wF(1866)(0)A-6.png" 
- "olea/Ole.O.euroX400wF(4261)(0)A-54.png"
- "origanum/Lam.O.micX400wF(884)(0)A-2.png"
