path_model: "/media/jczars/4C22F02A22F01B22/Pollen_classification_view/results/phase2/reports_cr_13_400/0_DenseNet201/0_DenseNet201_bestLoss_1.keras"
nome: "GradCAM_class_wrog_eq_k1.png"
conv_layer_name: "relu"
img_size: 224

path_data: "/media/jczars/4C22F02A22F01B22/Pollen_classification_view/BD/CPD1_Dn_VTcr_281124/EQUATORIAL_400/Test/k1/"
images_labels:
- "ceratonia/Fab.C.silX400wF(481)(0)G-6.png"
- "origanum/Lam.O.micX400wF(888)(0)E-6.png"

