path_model: "results/phase3/reports_cr_400/0_DenseNet201/0_DenseNet201_bestLoss_1.keras"
nome: "GradCAM_class_well1_k1.png"
conv_layer_name: "relu"
img_size: 224

path_data: "BD/CPD1_Cr_Rs/"
images_labels:
- "ceratonia/Fab.C.silX400wF(475)(0)A-12.png"
- "eucalyptus/Myr.E.camaX400wF(1868)(0)C-11.png" 
- "sinapis/Bra.S.albX400wF(2150)(0)A-14.png"
- "thymbra/x40 f (2)-1.png"
