tipo: "png"  # Image file type (e.g., 'jpg', 'png')
bd_src: "/media/jczars/4C22F02A22F01B22/01_PROP_TESE/01_BD_CPD1_CR/Cropped Pollen Grains/"  # Destination directory to save resized images
bd_dst: "./BD/CPD1_Is_Rc/"   # Directory to save the distribution chart
save_dir: "1_create_bd"  # Diretório para salvar o gráfico de distribuição
save: 1  # 1 to save resized images, 0 to not save
verbose: 1  # 1 for detailed output, 0 for silent mode
